In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv(R"dataset/titanic.csv")

In [4]:
df.head(3)

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

In [6]:
df['fare'].max()

512.3292

In [35]:
female =df[df['sex'] =='female']
male =df[df['sex'] =='male']

In [36]:
male.head()

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False

In [37]:
male.describe()

,Unnamed: 0,survived,pclass,age,sibsp,parch,fare
count,577.000000,577.000000,577.000000,453.000000,577.000000,577.000000,577.000000
mean,453.147314,0.188908,2.389948,30.726645,0.429809,0.235702,25.523893
std,257.486139,0.391775,0.813580,14.678201,1.061811,0.612294,43.138263
min,0.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,221.000000,0.000000,2.000000,21.000000,0.000000,0.000000,7.895800
50%,463.000000,0.000000,3.000000,29.000000,0.000000,0.000000,10.500000
75%,679.000000,0.000000,3.000000,39.000000,0.000000,0.000000,26.550000
max,890.000000,1.000000,3.000000,80.000000,8.000000,5.000000,512.329200

In [39]:
female.merge(male ,how='outer')

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
1,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
2,3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
3,8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
4,9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
887,884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
888,886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [41]:
df.groupby('class').groups

{'First': [1, 3, 6, 11, 23, 27, 30, 31, 34, 35, 52, 54, 55, 61, 62, 64, 83, 88, 92, 96, 97, 102, 110, 118, 124, 136, 137, 139, 151, 155, 166, 168, 170, 174, 177, 185, 187, 194, 195, 209, 215, 218, 224, 230, 245, 248, 252, 256, 257, 258, 262, 263, 268, 269, 270, 273, 275, 284, 290, 291, 295, 297, 298, 299, 305, 306, 307, 309, 310, 311, 318, 319, 325, 329, 331, 332, 334, 336, 337, 339, 341, 351, 356, 366, 369, 370, 373, 375, 377, 380, 383, 390, 393, 412, 430, 434, 435, 438, 445, 447, ...], 'Second': [9, 15, 17, 20, 21, 33, 41, 43, 53, 56, 58, 66, 70, 72, 78, 84, 98, 99, 117, 120, 122, 123, 133, 134, 135, 144, 145, 148, 149, 150, 161, 178, 181, 183, 190, 191, 193, 199, 211, 213, 217, 219, 221, 226, 228, 232, 234, 236, 237, 238, 239, 242, 247, 249, 259, 265, 272, 277, 288, 292, 303, 308, 312, 314, 316, 317, 322, 323, 327, 340, 342, 343, 344, 345, 346, 357, 361, 385, 387, 389, 397, 398, 399, 405, 407, 413, 416, 417, 418, 426, 427, 432, 437, 439, 440, 443, 446, 450, 458, 463, ...], 'Third': [0, 2, 4, 5, 7, 8, 10, 12, 13, 14, 16, 18, 19, 22, 24, 25, 26, 28, 29, 32, 36, 37, 38, 39, 40, 42, 44, 45, 46, 47, 48, 49, 50, 51, 57, 59, 60, 63, 65, 67, 68, 69, 71, 73, 74, 75, 76, 77, 79, 80, 81, 82, 85, 86, 87, 89, 90, 91, 93, 94, 95, 100, 101, 103, 104, 105, 106, 107, 108, 109, 111, 112, 113, 114, 115, 116, 119, 121, 125, 126, 127, 128, 129, 130, 131, 132, 138, 140, 141, 142, 143, 146, 147, 152, 153, 154, 156, 157, 158, 159, ...]}

In [44]:
df.groupby('class').get_group('First')

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
23,23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [47]:
df.groupby('class')['survived'].count()

class
First     216
Second    184
Third     491
Name: survived, dtype: int64

### splitting

In [56]:
d =df[['sex','age']].head(50)

In [57]:
d.head()

      sex   age
0    male  22.0
1  female  38.0
2  female  26.0
3  female  35.0
4    male  35.0

In [61]:
s =d.groupby('sex')

In [62]:
s.groups

{'female': [1, 2, 3, 8, 9, 10, 11, 14, 15, 18, 19, 22, 24, 25, 28, 31, 32, 38, 39, 40, 41, 43, 44, 47, 49], 'male': [0, 4, 5, 6, 7, 12, 13, 16, 17, 20, 21, 23, 26, 27, 29, 30, 33, 34, 35, 36, 37, 42, 45, 46, 48]}

In [64]:
s.get_group('female').head(3)

      sex   age
1  female  38.0
2  female  26.0
3  female  35.0

In [73]:
list(s)[1][1].head(3) # work as get group

    sex   age
0  male  22.0
4  male  35.0
5  male   NaN

In [107]:
d =df.iloc[:50,[3,4,9]]

In [83]:
d.groupby(['sex','class'])['age'].mean()

sex     class
female  First     36.500000
        Second    14.000000
        Third     26.500000
male    First     54.000000
        Third     19.666667
Name: age, dtype: float64

In [84]:
d.groupby(['sex','class']).groups

{('female', 'First'): [1, 3], ('female', 'Second'): [9], ('female', 'Third'): [2, 8], ('male', 'First'): [6], ('male', 'Third'): [0, 4, 5, 7]}

In [89]:
d.groupby(['sex','class']).get_group(('female','Third'))

      sex   age  class
2  female  26.0  Third
8  female  27.0  Third

In [92]:
list(d.groupby(['sex','class']))[0][1]

      sex   age  class
1  female  38.0  First
3  female  35.0  First

In [110]:
dsum=d.groupby(['class','sex']).sum()

In [111]:
dsum

                 age
class  sex
First  female  131.0
       male    211.0
Second female   99.0
       male    135.0
Third  female  272.0
       male    141.0

In [103]:
dsum.index

MultiIndex([( 'First', 'female'),
            ( 'First',   'male'),
            ('Second', 'female'),
            ( 'Third', 'female'),
            ( 'Third',   'male')],
           names=['class', 'sex'])

In [112]:
dsum.loc['First']

          age
sex
female  131.0
male    211.0

In [115]:
dsum.iloc[2,:]

age    99.0
Name: (Second, female), dtype: float64

### using agg() function

In [116]:
d =df.loc[:,['survived','pclass','sex','age','fare']]

In [118]:
d.head()

   survived  pclass     sex   age     fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [120]:
d.groupby('sex').agg(['mean','max'])

        survived        pclass            age             fare
            mean max      mean max       mean   max       mean       max
sex
female  0.742038   1  2.159236   3  27.915709  63.0  44.479818  512.3292
male    0.188908   1  2.389948   3  30.726645  80.0  25.523893  512.3292

In [121]:
d.groupby('sex').agg({'survived':['mean','max'],'age':['sum','count']})

        survived           age
            mean max       sum count
sex
female  0.742038   1   7286.00   261
male    0.188908   1  13919.17   453

In [126]:
d.groupby('sex').agg(survived_name =('survived','sum'))

        survived_name
sex
female            233
male              109

# pivoting

### wide to long

In [3]:
df.head(3)

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

###### what is the value that column sex have , mean

In [21]:
df.pivot_table(index='sex',columns='pclass',values='fare')

pclass           1          2       3
sex
female  103.128209  14.865744  13.360
male     76.445333  23.812500   8.695

In [9]:
df['sex'] = df['sex'].astype('string')

In [52]:
pd.pivot_table(df, index='sex',values='age')

              age
sex
female  32.676136
male    38.382128

In [47]:
df['embarked'].value_counts()

embarked
S    115
C     65
Q      2
Name: count, dtype: Int64

In [73]:
df.pivot_table(index=['sex','pclass'])['fare']

sex     pclass
female  1         103.128209
        2          14.865744
        3          13.360000
male    1          76.445333
        2          23.812500
        3           8.695000
Name: fare, dtype: float64

In [69]:
df.groupby(['sex','pclass'])['fare'].mean()

sex     pclass
female  1         103.128209
        2          14.865744
        3          13.360000
male    1          76.445333
        2          23.812500
        3           8.695000
Name: fare, dtype: float64

In [74]:
df.pivot_table(index=['sex','pclass'])

                     age        fare     parch     sibsp  survived
sex    pclass
female 1       34.094595  103.128209  0.554054  0.581081  0.959459
       2       29.611111   14.865744  0.111111  0.222222  0.888889
       3       17.200000   13.360000  1.200000  0.400000  0.600000
male   1       40.619518   76.445333  0.397590  0.409639  0.421687
       2       18.750000   23.812500  0.833333  0.666667  0.666667
       3       24.800000    8.695000  0.200000  0.000000  0.400000

In [78]:
df.pivot_table(index=['sex','pclass'],aggfunc=np.sum,margins=True) # for all row (margins=True)

                   age        fare  parch  sibsp  survived
sex    pclass
female 1       2523.00   7631.4875     41     43        71
       2        266.50    133.7917      1      2         8
       3         86.00     66.8000      6      2         3
male   1       3371.42   6344.9626     33     34        35
       2        112.50    142.8750      5      4         4
       3        124.00     43.4750      1      0         2
All            6483.42  14363.3918     87     85       123

In [90]:
e =df.pivot_table(index=['sex','pclass'],values='fare',aggfunc=np.sum,margins=True) # for all row (margins=True)

In [91]:
e

                     fare
sex    pclass
female 1        9975.8250
       2        1669.7292
       3        2321.1086
male   1        8201.5875
       2        2132.1125
       3        4393.5865
All            28693.9493

In [80]:
df.pivot_table(index=['sex'],columns='pclass',values='fare',aggfunc=np.sum,margins=True) # for all row (margins=True)

pclass           1         2        3         All
sex
female   7631.4875  133.7917   66.800   7832.0792
male     6344.9626  142.8750   43.475   6531.3126
All     13976.4501  276.6667  110.275  14363.3918

In [81]:
df = pd.read_csv(R"dataset/titanic.csv")

In [87]:
s=pd.pivot_table(df,index=['sex','survived','pclass']
              ,columns=['embark_town'],values=['age'],
              aggfunc=np.sum,margins=True,fill_value=np.mean(df.age))

In [88]:
s

                                age
embark_town               Cherbourg  Queenstown Southampton       All
sex    survived pclass
female 0        1         50.000000   29.699118       27.00     77.00
                2         29.699118   29.699118      216.00    216.00
                3        103.500000  140.500000     1066.00   1310.00
       1        1       1320.000000   33.000000     1412.00   2765.00
                2        134.000000   30.000000     1745.50   1909.50
                3        121.500000   88.000000      699.00    908.50
male   0        1        861.000000   44.000000     1814.50   2719.50
                2        206.500000   57.000000     2539.50   2803.00
                3        496.000000  365.000000     4999.00   5860.00
       1        1        583.000000   29.699118      866.92   1449.92
                2          1.000000   29.699118      239.33    240.33
                3        129.420000   29.000000      688.00    846.42
All                     4005.920000  786.500000    16312.75  21105.17

In [92]:
e

                     fare
sex    pclass
female 1        9975.8250
       2        1669.7292
       3        2321.1086
male   1        8201.5875
       2        2132.1125
       3        4393.5865
All            28693.9493

In [ ]:
e.melt(id_vars=['sex','pclass'])