In [195]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
# Regression
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
# Classifiction
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsOneClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
import warnings
warnings.filterwarnings('ignore')

In [196]:
data = pd.read_excel(R"C:\Users\G.B\Desktop\osam\المرحلة الثانية\data science\dataset\cleaner.xlsx")

In [197]:
data.head()

   ss       Open       High        Low  Close  Adj Close  Volume
0   0  45.590000  49.840000  45.020000    NaN  49.139999     NaN
1   1  48.900002  52.580002  48.700001    NaN  51.990002     NaN
2   2  52.400002  53.869999  51.000000    NaN  52.340000     NaN
3   3  52.200001  55.869999  50.689999    NaN  55.330002     NaN
4   4  56.200001  59.410000  55.450001    NaN  59.000000     NaN

In [198]:
data = data.drop(["ss","Adj Close","Volume"],axis=1)

In [200]:
data = data.dropna()

In [201]:
data.isnull().sum()

Open     0
High     0
Low      0
Close    0
dtype: int64

In [192]:
s = 2
type(s)==float

False

In [202]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.75,random_state=40)

In [203]:
y

99      39.020000
100     38.750000
101     31.850000
102     30.660000
103     31.959999
          ...
2233    49.889999
2234    51.520000
2235    52.779999
2236    53.349998
2237    53.700001
Name: Close, Length: 2139, dtype: float64

In [204]:
model0=LinearRegression()
model1=MLPRegressor(activation='tanh',max_iter=1000)
model2=DecisionTreeRegressor(max_depth=1000)
model3=RandomForestRegressor(n_estimators=1000,max_depth=1000)
model4=KNeighborsRegressor(n_neighbors=10)
#-------------------------------
model0.fit(x_train,y_train)
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)
model4.fit(x_train,y_train)
#-------------------------------

KNeighborsRegressor(n_neighbors=10)

In [205]:
print(model0.score(x_train,y_train))
print(model1.score(x_train,y_train))
print(model2.score(x_train,y_train))
print(model3.score(x_train,y_train))
print(model4.score(x_train,y_train))

0.9991053881981695
0.9938684622546047
1.0
0.9997744842934617
0.998615609846533

In [206]:
#--------------------------------------
print(model0.score(x_test,y_test))
print(model1.score(x_test,y_test))
print(model2.score(x_test,y_test))
print(model3.score(x_test,y_test))
print(model4.score(x_test,y_test))

0.9992740062460923
0.993611133394487
0.9980069322398746
0.9988929780360287
0.9988086570133182

In [207]:
x_test

           Open       High        Low
990   20.160000  20.305000  19.930000
876   18.530001  18.580000  18.219999
1651  30.150000  31.170000  30.059999
1018  25.030001  25.270000  24.379999
525   20.120001  20.200001  19.260000
...         ...        ...        ...
2046  34.220001  34.990002  33.619999
2224  49.660000  50.860001  49.500000
383   34.630001  35.040001  34.450001
450   26.969999  27.280001  26.575001
2083  37.459999  39.044998  37.180000

[535 rows x 3 columns]

In [208]:
y_test

990     20.170000
876     18.309999
1651    30.809999
1018    24.459999
525     19.650000
          ...
2046    34.169998
2224    50.360001
383     34.660000
450     26.790001
2083    37.770000
Name: Close, Length: 535, dtype: float64

In [209]:
model3.predict(x_test)

array([20.13154025, 18.39319018, 30.59343996, 24.80535969, 19.60185018,
       50.56288964, 17.33220015, 39.02501953, 48.71469032, 32.75378963,
       42.40761092, 29.96211981, 14.29377   , 46.40600938, 29.96571962,
       48.57923092, 33.12906938, 41.71104977, 17.88847047, 63.38604935,
       28.30958011, 33.17063962, 35.88724955, 36.88220009, 39.30229032,
       35.11396929, 26.46946979, 27.95619018, 44.01241059, 17.45042069,
       24.70772014, 33.02769935, 39.71050947, 30.25956962, 31.24173955,
       40.40256006, 35.32801999, 37.73423007, 17.85225032, 18.25360979,
       32.96481988, 24.04297996, 39.29382999, 60.89311028, 16.91714991,
       35.13976935, 33.66717023, 17.6236101 , 48.97024062, 47.93253   ,
       19.04200009, 33.78514082, 40.48087972, 37.15918025, 15.06195   ,
       34.15303058, 35.82904986, 29.20567965, 35.98880024, 35.95956971,
       14.69532   , 38.30818028, 23.12730983, 37.62062022, 43.68389112,
       17.96014026, 33.24962963, 16.63074003, 25.27175027, 40.66743076,
       31.21975963, 32.95718977, 34.28133951, 29.41350969, 37.3156405 ,
       17.69296042, 47.4708701 , 18.28820982, 27.52951981, 15.09618   ,
       37.39910947, 27.54798962, 24.44192003, 37.43525974, 14.2337    ,
       24.06860998, 18.33124964, 18.00535   , 18.59883945, 37.84873052,
       23.18203966, 67.85977948, 28.31897939, 29.24850974, 29.89643988,
       17.68721009, 33.1735491 , 36.83749949, 35.62232039, 14.34951   ,
       63.13870039, 26.80604986, 32.62057985, 68.60629011, 35.75293949,
       37.56484056, 32.22453015, 35.19025957, 21.60529993, 43.51690968,
       32.30062982, 44.12777963, 29.91827979, 37.70245955, 39.33712004,
       41.66203043, 28.95107971, 21.67465992, 31.55531005, 32.58997035,
       29.09959952, 33.71680057, 52.6716102 , 38.04427011, 27.59616977,
       42.28928065, 14.27586   , 45.15488   , 16.01818994, 15.06655   ,
       14.34377   , 53.93485031, 42.15342952, 22.43843003, 68.23881103,
       32.71794036, 26.15095007, 31.13734986, 45.29159017, 70.27268995,
       18.39328009, 18.08925995, 16.92090975, 29.84535963, 30.96647967,
       24.32415999, 23.92420997, 17.7744101 , 47.10465011, 37.38294935,
       32.83087904, 29.22435963, 40.99529047, 46.24112002, 45.82945039,
       19.19969015, 31.96108007, 22.29361009, 60.38441967, 41.49532973,
       35.8065608 , 44.09277095, 14.63333   , 14.45718   , 45.53535985,
       31.19804978, 50.25316088, 18.53699949, 29.72997023, 17.78280019,
       36.04083979, 32.50324961, 25.32581021, 35.16196989, 32.24510032,
       18.23727009, 24.73400944, 39.52948005, 17.55913009, 16.9400797 ,
       31.74593005, 18.3421398 , 29.95761962, 33.8471309 , 17.78053989,
       36.24559046, 20.21873021, 32.6991705 , 67.23121083, 33.9684203 ,
       29.40472985, 51.81277987, 30.81794976, 18.5677394 , 27.51469966,
       18.14313013, 40.05176977, 46.76449001, 36.8315991 , 23.00823953,
       35.96215982, 53.81751005, 48.73628996, 31.62163006, 35.12253975,
       59.96749929, 41.52436016, 44.10913982, 32.98321925, 28.62815993,
       32.23868947, 39.90190961, 38.67194064, 34.51911019, 41.49084974,
       69.31019872, 69.22658894, 70.78292985, 37.54548981, 50.2827802 ,
       62.76465991, 37.02864981, 18.25383991, 44.10437945, 24.2612301 ,
       14.48983   , 25.38588039, 16.5000799 , 45.84150058, 62.31084939,
       16.89959965, 39.47750996, 35.93939928, 66.11693926, 59.70214046,
       45.32848031, 16.84404008, 32.11716954, 65.10637881, 28.54567978,
       36.9884393 , 18.31510986, 17.03714054, 29.34262984, 29.99154944,
       29.5101101 , 31.64677012, 43.04539979, 50.30409016, 47.46614005,
       37.52567063, 41.23764024, 28.98105987, 41.87979989, 49.29685097,
       64.79716214, 16.71385986, 69.03422766, 38.65373032, 41.32736997,
       37.79710038, 37.83479011, 54.24641033, 29.72602049, 29.28849993,
       33.38003998, 39.49592013, 62.7465208 , 30.33563949, 29.72310967,
       32.09597957, 34.43253016, 38.71213894, 39.90150964, 27.26291974,
       38.94871968, 39.5963195 , 16.05593982, 64.24691009, 49.36825007,
       22.85606979, 48.80359035, 18.06255011, 31.03734002, 51.67195998,
       35.6107797 , 25.03869026, 50.31070037, 44.24467017, 53.58537163,
       43.56324026, 42.07963023, 44.09416022, 54.36630985, 75.2075872 ,
       18.42500979, 48.43723981, 29.2495996 , 27.60680966, 39.6452193 ,
       18.35365964, 69.79162044, 33.75852997, 26.05085997, 18.62254009,
       15.20977   , 53.82394054, 24.20807069, 39.37816999, 27.87807036,
       14.24281   , 32.58783971, 29.38997008, 29.34000976, 46.65348956,
       27.08849976, 40.35797041, 39.81443956, 40.74741091, 43.77054063,
       34.45591022, 25.45075034, 16.02296998, 24.14331068, 39.39128972,
       40.56811991, 18.04383988, 41.50778   , 41.60271006, 28.59454985,
       14.29547   , 51.03304066, 18.3228799 , 31.17216977, 31.8373    ,
       16.76234003, 32.70873016, 33.75925072, 49.58209035, 30.66051987,
       54.18609022, 43.37149978, 47.50359963, 50.60946075, 33.49879003,
       36.24686974, 30.32616002, 41.06923009, 14.29879   , 52.25451925,
       34.75906035, 41.57041043, 17.6883306 , 38.2263998 , 43.63491031,
       29.76226028, 71.25113138, 57.66977026, 32.99264993, 43.91220998,
       41.90583997, 71.18614152, 32.34138945, 16.53299005, 26.28912002,
       51.28538013, 29.5441    , 33.39051995, 25.47587027, 36.85268926,
       18.02349019, 28.4552796 , 70.24284961, 18.53410003, 38.6963101 ,
       18.04843031, 66.14167006, 28.87404018, 38.69852081, 34.11684981,
       17.79552019, 55.79335959, 52.28646974, 45.0861194 , 37.49104046,
       68.55653046, 28.76542971, 54.35769103, 33.67868007, 15.0948    ,
       50.94426036, 37.82908086, 37.35172925, 35.48280966, 47.33084915,
       32.93372926, 40.52789975, 32.80916949, 62.91932081, 42.81657041,
       36.65770009, 43.26738983, 16.52333016, 18.09080982, 67.7599995 ,
       36.26872015, 31.66523984, 64.78868033, 14.5742    , 16.93873016,
       45.03673956, 46.18620984, 35.37941058, 30.70405022, 14.24281   ,
       35.75633972, 66.54480007, 37.88492036, 38.9456006 , 29.94129003,
       28.31110013, 38.87431919, 26.24212944, 18.64720024, 47.23836029,
       69.33263923, 63.61173025, 16.07061023, 65.55903952, 28.72900953,
       15.30425   , 68.91059854, 43.59469949, 27.67458027, 33.60388966,
       18.34833998, 44.04015992, 18.62026934, 18.16727011, 29.27417035,
       51.09646986, 40.42983028, 31.70884999, 30.65349991, 18.04649025,
       42.36393973, 59.77241023, 32.9691295 , 30.94278977, 39.54836009,
       32.07834969, 38.93602942, 45.41715013, 14.76731   , 36.03574013,
       18.9179101 , 37.43147978, 18.37698965, 36.05646003, 24.97191039,
       35.25492905, 46.34441955, 20.66483992, 18.10511009, 40.68997991,
       40.30704047, 69.87833909, 44.06728025, 43.20186085, 32.44381944,
       31.05155005, 62.33948007, 49.58759048, 18.29129004, 39.53644018,
       62.66638993, 32.25026979, 38.73837028, 67.37710972, 43.0596098 ,
       28.98023986, 34.67114111, 26.72152988, 16.66308027, 30.41062997,
       18.10552997, 32.24921072, 29.3226695 , 23.04842969, 18.14567034,
       34.40595019, 38.76373031, 33.26986118, 22.38436986, 31.35596009,
       54.35201024, 34.26897014, 46.18658994, 33.24523973, 61.14324047,
       36.72392098, 36.8271301 , 25.79157   , 16.49036974, 15.80470991,
       17.04665009, 36.31149052, 70.06388953, 64.85591874, 50.30340027,
       39.22373985, 72.15079922, 44.52151974, 55.58520944, 41.73772979,
       58.16118001, 50.6812707 , 42.08655017, 14.34376   , 30.77408005,
       34.79602959, 52.31273909, 25.3757598 , 49.09680991, 47.41039995,
       40.54385002, 36.53480873, 60.40138899, 18.16095002, 30.83408992,
       34.31111018, 50.33681038, 34.85576047, 26.83136004, 37.84893994])

In [210]:
data1 = pd.read_excel(R"C:\Users\G.B\Desktop\osam\المرحلة الثانية\data science\dataset\nullclean.xlsx")

In [211]:
data1

         Open       High        Low  Close
0   45.590000  49.840000  45.020000    NaN
1   48.900002  52.580002  48.700001    NaN
2   52.400002  53.869999  51.000000    NaN
3   52.200001  55.869999  50.689999    NaN
4   56.200001  59.410000  55.450001    NaN
..        ...        ...        ...    ...
94  44.290001  44.439999  41.310001    NaN
95  41.759998  42.349998  39.299999    NaN
96  40.529999  43.970001  40.174999    NaN
97  37.660000  38.980000  37.240002    NaN
98  39.009998  40.770000  38.966000    NaN

[99 rows x 4 columns]

In [212]:
data1 = data1.drop(["Close"],axis=1)

In [213]:
data1

         Open       High        Low
0   45.590000  49.840000  45.020000
1   48.900002  52.580002  48.700001
2   52.400002  53.869999  51.000000
3   52.200001  55.869999  50.689999
4   56.200001  59.410000  55.450001
..        ...        ...        ...
94  44.290001  44.439999  41.310001
95  41.759998  42.349998  39.299999
96  40.529999  43.970001  40.174999
97  37.660000  38.980000  37.240002
98  39.009998  40.770000  38.966000

[99 rows x 3 columns]

In [214]:
model3.predict(data1)

array([48.06011029, 51.22677018, 52.24982054, 51.93228053, 57.28545914,
       58.08767011, 56.75151961, 55.56811939, 56.17067998, 59.06310082,
       62.56422967, 67.76890942, 71.44203923, 66.06013032, 61.39415028,
       63.55844948, 66.29962021, 69.40914872, 65.82225021, 65.90624798,
       59.20944047, 58.31395979, 57.61214913, 58.77729001, 58.62745042,
       60.69460069, 61.96916069, 62.93668033, 62.13102978, 62.63056011,
       61.95867076, 62.56284031, 59.25658003, 58.76270995, 59.69790982,
       64.26341983, 64.28176853, 65.00788941, 65.07499961, 65.7977804 ,
       52.21813001, 52.35618003, 53.72253032, 53.8287407 , 56.32100023,
       57.04747895, 57.18362967, 57.73629012, 57.6603598 , 56.19267026,
       56.85892934, 56.3094994 , 55.77490949, 56.22599008, 56.3604294 ,
       54.51319967, 53.6396611 , 54.42821062, 54.19445118, 56.15418977,
       54.31439103, 53.77888074, 54.18947059, 54.23064081, 54.3092809 ,
       52.36369076, 51.87747934, 50.79506065, 51.35590011, 50.06665021,
       50.32445015, 49.16878006, 48.30046028, 45.25137097, 44.38394048,
       46.07690929, 47.3555098 , 47.34166995, 46.14380883, 44.17035893,
       44.06517035, 43.92944016, 42.19231956, 42.67141035, 41.61074989,
       40.4906504 , 40.54424015, 42.75373995, 44.16585928, 44.84412077,
       45.87171918, 46.58231931, 45.69420012, 44.52350065, 42.05269036,
       40.92226994, 41.95738998, 38.05657023, 40.21224019])

In [217]:
data2 = pd.read_csv(R"C:\Users\G.B\Desktop\osam\المرحلة الثانية\data science\dataset\TWTR.csv")

In [221]:
data2["Close"].head(7)

0    49.139999
1    51.990002
2    52.340000
3    55.330002
4    59.000000
5    56.610001
6    56.450001
Name: Close, dtype: float64