In [1]:
import keras

WARNING:tensorflow:From C:\Users\G.B\anaconda3\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.layers import Conv2D,MaxPooling2D,Dropout,Flatten,Dense,Activation,BatchNormalization
import tensorflow as tf

from sklearn.model_selection import train_test_split

WARNING:tensorflow:From C:\Users\G.B\anaconda3\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
data =pd.read_csv(R"C:\Users\G.B\Desktop\osam\المرحلة الثانية\data science\dataset\heart_failure_clinical_records_dataset.csv")

In [3]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [4]:
xtrain,xtemp,ytrain,ytemp=train_test_split(x,y,test_size=0.4)
xtest,xvalid,ytest,yvalid=train_test_split(x,y,test_size=0.5)

In [5]:
xtrain.shape

(179, 12)

In [6]:
model = Sequential()
model.add(Dense(64, input_dim=40,activation = "relu")) #Layer 1
model.add(Dense(32,activation = "relu"))  #Layer 2
model.add(Dense(16,activation = "relu"))  #Layer 3
model.add(Dense(8,activation = "relu"))  #Layer 4
model.add(Dense(4,activation = "relu"))  #Layer 5
model.add(Dense(1,activation = "sigmoid"))  #Output Layer
#Configure the model
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

WARNING:tensorflow:From C:\Users\G.B\anaconda3\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From C:\Users\G.B\anaconda3\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                2624

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 16)                528

 dense_3 (Dense)             (None, 8)                 136

 dense_4 (Dense)             (None, 4)                 36

 dense_5 (Dense)             (None, 1)                 5

=================================================================
Total params: 5409 (21.13 KB)
Trainable params: 5409 (21.13 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [7]:
model = tf.keras.Sequential([
tf.keras.layers.Dense(16,activation = "relu",), #Layer 1
tf.keras.layers.Dense(16,activation = "relu"), 
tf.keras.layers.Dense(1,activation = "sigmoid")
])  
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss=tf.keras.losses.BinaryCrossentropy(),metrics=['accuracy'])

In [8]:
model.evaluate(xtrain,ytrain)

WARNING:tensorflow:From C:\Users\G.B\anaconda3\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From C:\Users\G.B\anaconda3\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

6/6 [==============================] - 2s 12ms/step - loss: 12123.8379 - accuracy: 0.6648

[12123.837890625, 0.6648044586181641]

In [9]:
model.fit(xtrain, ytrain, batch_size=64, epochs=10,validation_data=(xvalid,yvalid))

Epoch 1/10
3/3 [==============================] - 1s 91ms/step - loss: 11173.6475 - accuracy: 0.6648 - val_loss: 7859.7285 - val_accuracy: 0.6933
Epoch 2/10
3/3 [==============================] - 0s 30ms/step - loss: 8050.1230 - accuracy: 0.6648 - val_loss: 5212.2344 - val_accuracy: 0.6933
Epoch 3/10
3/3 [==============================] - 0s 34ms/step - loss: 5154.2007 - accuracy: 0.6648 - val_loss: 2584.0891 - val_accuracy: 0.6933
Epoch 4/10
3/3 [==============================] - 0s 35ms/step - loss: 1955.8575 - accuracy: 0.6648 - val_loss: 122.3020 - val_accuracy: 0.6933
Epoch 5/10
3/3 [==============================] - 0s 44ms/step - loss: 1334.3495 - accuracy: 0.4860 - val_loss: 3132.5508 - val_accuracy: 0.3067
Epoch 6/10
3/3 [==============================] - 0s 42ms/step - loss: 2913.1729 - accuracy: 0.3352 - val_loss: 2129.9976 - val_accuracy: 0.3067
Epoch 7/10
3/3 [==============================] - 0s 46ms/step - loss: 1210.8650 - accuracy: 0.3352 - val_loss: 395.1951 - val_accuracy: 0.6933
Epoch 8/10
3/3 [==============================] - 0s 45ms/step - loss: 801.7205 - accuracy: 0.6648 - val_loss: 1278.9658 - val_accuracy: 0.6933
Epoch 9/10
3/3 [==============================] - 0s 46ms/step - loss: 1572.3258 - accuracy: 0.6648 - val_loss: 1422.1636 - val_accuracy: 0.6933
Epoch 10/10
3/3 [==============================] - 0s 53ms/step - loss: 1525.4989 - accuracy: 0.6648 - val_loss: 996.6100 - val_accuracy: 0.6933

In [11]:
xtrain

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time
275,45.0,0,582,0,38,1,422000.00,0.80,137,0,0,245
29,82.0,0,70,1,30,0,200000.00,1.20,132,1,1,26
287,45.0,0,582,1,55,0,543000.00,1.00,132,0,0,250
176,69.0,0,1419,0,40,0,105000.00,1.00,135,1,1,147
60,45.0,0,7702,1,25,1,390000.00,1.00,139,1,0,60
...,...,...,...,...,...,...,...,...,...,...,...,...
183,75.0,0,99,0,38,1,224000.00,2.50,134,1,0,162
289,90.0,1,337,0,38,0,390000.00,0.90,144,0,0,256
135,75.0,0,582,0,40,0,263358.03,1.18,137,1,0,107
47,60.0,0,582,1,38,1,451000.00,0.60,138,1,1,40
270,44.0,0,582,1,30,1,263358.03,1.60,130,1,1,244

In [14]:
ytrain

275    0
29     1
287    0
176    0
60     1
      ..
183    1
289    0
135    0
47     1
270    0
Name: DEATH_EVENT, Length: 179, dtype: int64

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time
159,59.0,1,129,0,45,1,362000.0,1.1,139,1,1,121
65,60.0,0,68,0,20,0,119000.0,2.9,127,1,1,64
70,41.0,0,148,0,40,0,374000.0,0.8,140,1,1,68
251,55.0,0,572,1,35,0,231000.0,0.8,143,0,0,215
212,78.0,0,224,0,50,0,481000.0,1.4,138,1,1,192
...,...,...,...,...,...,...,...,...,...,...,...,...
261,62.0,1,655,0,40,0,283000.0,0.7,133,0,0,233
275,45.0,0,582,0,38,1,422000.0,0.8,137,0,0,245
75,60.0,1,47,0,20,0,204000.0,0.7,139,1,1,73
151,62.0,0,30,1,60,1,244000.0,0.9,139,1,0,117
182,65.0,0,395,1,25,0,265000.0,1.2,136,1,1,154

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time
276,70.0,0,618,0,35,0,327000.0,1.1,142,0,0,245
125,43.0,1,358,0,50,0,237000.0,1.3,135,0,0,97
2,65.0,0,146,0,20,0,162000.0,1.3,129,1,1,7
46,51.0,0,1380,0,25,1,271000.0,0.9,130,1,0,38
167,59.0,0,66,1,20,0,70000.0,2.4,134,1,0,135
...,...,...,...,...,...,...,...,...,...,...,...,...
113,70.0,1,143,0,60,0,351000.0,1.3,137,0,0,90
44,60.0,1,588,1,60,0,194000.0,1.1,142,0,0,33
3,50.0,1,111,0,20,0,210000.0,1.9,137,1,0,7
228,65.0,0,56,0,25,0,237000.0,5.0,130,0,0,207
181,59.0,1,176,1,25,0,221000.0,1.0,136,1,1,150

In [21]:
ytest

159    0
65     1
70     0
251    0
212    0
      ..
261    0
275    0
75     1
151    0
182    1
Name: DEATH_EVENT, Length: 149, dtype: int64

In [20]:
model.predict(xtest)

5/5 [==============================] - 0s 2ms/step

array([[0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [3.525375e-30],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00],
       [0.000000e+00]], dtype=float32)

In [13]:
model.predict([[45.0, 0 ,582, 0, 38, 1, 422000.00, 0.80, 137, 0 ,0 ,245]])

1/1 [==============================] - 0s 152ms/step

array([[0.]], dtype=float32)

In [15]:
# Sequential mean layers
model =Sequential()
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(179,179,3)))
model.add(MaxPooling2D(2,2))

model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPooling2D(2,2))


model.add(Conv2D(128,(3,3),activation='relu'))
model.add(MaxPooling2D(2,2))

model.add(Conv2D(128,(3,3),activation='relu'))
model.add(MaxPooling2D(2,2))

model.add(Flatten())
model.add(Dense(512,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='categorical_crossentropy',optimizer='rmsprop',metrics=['accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d_3 (Conv2D)           (None, 177, 177, 32)      896

 max_pooling2d_2 (MaxPoolin  (None, 88, 88, 32)        0
 g2D)

 conv2d_4 (Conv2D)           (None, 86, 86, 64)        18496

 max_pooling2d_3 (MaxPoolin  (None, 43, 43, 64)        0
 g2D)

 conv2d_5 (Conv2D)           (None, 41, 41, 128)       73856

 max_pooling2d_4 (MaxPoolin  (None, 20, 20, 128)       0
 g2D)

 conv2d_6 (Conv2D)           (None, 18, 18, 128)       147584

 max_pooling2d_5 (MaxPoolin  (None, 9, 9, 128)         0
 g2D)

 flatten (Flatten)           (None, 10368)             0

 dense_9 (Dense)             (None, 512)               5308928

 dense_10 (Dense)            (None, 1)                 513

=================================================================
Total params: 5550273 (21.17 MB)
Trainable params: 5550273 (21.17 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________